trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: detect_release
    steps:
    - bash: 
      name: setvarStep
    - bash: |
       echo github_version : {$(setvarStep.github_version)}

       echo 'Get Last release tag (Github) : '
       curl -s -H "Accept: application/vnd.github.v3+json" \
         "https://api.github.com/repos/vincent-herlemont/short/releases/latest"
          
       echo 'Get current release tag (Cargo.toml) :'
       cargo metadata --format-version 1 --manifest-path Cargo.toml \
         | jq -r '.packages[] | select(.name | test("short")) | .version'
      displayName: 'Reatrieve version github / Cargo.toml'
    - bash: |
        echo github_version : {$(setvarStep.github_version)}


  - job: github_release
    variables:
      github_version: $[ dependencies.detect_release.outputs['setvarStep.github_version'] ]
    dependsOn: detect_release
    condition: and(succeeded('detect_release'), ne(dependencies.detect_release.outputs['setvarStep.github_version'], '0.0.1'))
    steps:
    - bash: | 
       echo "OK"
       echo github_version : {$(github_version)}

