[package]
name = "short"
version = "0.0.2"
authors = ["Vincent Herlemont <vincentherl@leszeros.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
thiserror = "1.0.19"
log = "0.4.8"
env_logger = "0.7.1"
open = "1.4.0"
tempdir = "0.3.7"
fs_extra = "1.1.0"
walkdir = "2.3.1"
serde_yaml ="0.8.13"
serde = { version = "1.0.112", features = ["derive","rc"] }
regex = "1.3.9"
clap = "2.33.0"
dirs = "2.0.2"
console = "0.11.2"
term-table = "1.3.0"
filetime = "0.2.10"
git2 = "0.13"
serde_json = "1.0.55"

[dev-dependencies]
predicates = "1.0.4"
cli_integration_test = "0.2.2"

[lib]
name = "short"
path = "src/lib.rs"
doc = true

[[bin]]
name = "short"
path = "src/main.rs"
doc = false