AWSTemplateFormatVersion: 2010-09-09
Description: "bucket that contains deployment assets"

Parameters:
  BucketName:
    Type: String
    Description: "bucket name"

Resources:
  DeployBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref BucketName

Outputs:
  DeployBucket:
    Value: !Ref DeployBucket