[package]
name = "short"
version = "0.0.2"
authors = ["Vincent Herlemont <vincentherl@leszeros.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"


[dev-dependencies]
walkdir = "2.3.1"
insta = "0.16.0"

[[bin]]
name = "short"
path = "src/main.rs"

[build-dependencies]
include_walk = "0.3.1"
