[package]
name = "cli"
version = "0.1.0"
authors = ["Vincent Herlemont <vincentherl@leszeros.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
dirs = "2.0.2"
utils = { path = "../utils" }
d4d = { path = "../d4d" }

[dev-dependencies]
walkdir = "2.3.1"
insta = "0.15.0"

[build-dependencies]
include_walk = "0.3.0"
