use utils::asset::Asset;

/// Get all [`Asset`]
#[allow(dead_code)]
pub fn get_assets() -> Vec<Asset> {
    vec![
        Asset::new(
            "assets/other_conf.yaml",
            include_str!("assets/other_conf.yaml"),
        ),
        Asset::new(
            "assets/altered_aws_template.yaml",
            include_str!("assets/altered_aws_template.yaml"),
        ),
        Asset::new(
            "assets/validate_aws_template.yaml",
            include_str!("assets/validate_aws_template.yaml"),
        ),
        Asset::new(
            "assets/tpl_bucket_template/steps.sh",
            include_str!("assets/tpl_bucket_template/steps.sh"),
        ),
        Asset::new(
            "assets/tpl_bucket_template/bucket_template.yaml",
            include_str!("assets/tpl_bucket_template/bucket_template.yaml"),
        ),
        Asset::new(
            "assets/sam_test/.gitignore",
            include_str!("assets/sam_test/.gitignore"),
        ),
        Asset::new(
            "assets/sam_test/steps.sh",
            include_str!("assets/sam_test/steps.sh"),
        ),
        Asset::new(
            "assets/sam_test/README.md",
            include_str!("assets/sam_test/README.md"),
        ),
        Asset::new(
            "assets/sam_test/template.yaml",
            include_str!("assets/sam_test/template.yaml"),
        ),
        Asset::new(
            "assets/sam_test/template.pkg.cf.yaml",
            include_str!("assets/sam_test/template.pkg.cf.yaml"),
        ),
        Asset::new(
            "assets/sam_test/template.pkg.sam.yaml",
            include_str!("assets/sam_test/template.pkg.sam.yaml"),
        ),
        Asset::new(
            "assets/sam_test/events/event.json",
            include_str!("assets/sam_test/events/event.json"),
        ),
        Asset::new(
            "assets/sam_test/hello-world/app.js",
            include_str!("assets/sam_test/hello-world/app.js"),
        ),
        Asset::new(
            "assets/sam_test/hello-world/package.json",
            include_str!("assets/sam_test/hello-world/package.json"),
        ),
        Asset::new(
            "assets/sam_test/hello-world/.npmignore",
            include_str!("assets/sam_test/hello-world/.npmignore"),
        ),
        Asset::new(
            "assets/sam_test/hello-world/tests/unit/test-handler.js",
            include_str!("assets/sam_test/hello-world/tests/unit/test-handler.js"),
        ),
        Asset::new(
            "assets/test/test.js",
            include_str!("assets/test/test.js"),
        ),
        Asset::new(
            "assets/tpl_certificate/steps.sh",
            include_str!("assets/tpl_certificate/steps.sh"),
        ),
        Asset::new(
            "assets/tpl_certificate/certificate.pkg.yaml",
            include_str!("assets/tpl_certificate/certificate.pkg.yaml"),
        ),
        Asset::new(
            "assets/tpl_certificate/certificate.yaml",
            include_str!("assets/tpl_certificate/certificate.yaml"),
        ),
        Asset::new(
            "assets/tpl_nested/steps.sh",
            include_str!("assets/tpl_nested/steps.sh"),
        ),
        Asset::new(
            "assets/tpl_nested/main.pkg.yaml",
            include_str!("assets/tpl_nested/main.pkg.yaml"),
        ),
        Asset::new(
            "assets/tpl_nested/main.yaml",
            include_str!("assets/tpl_nested/main.yaml"),
        ),
        Asset::new(
            "assets/tpl_nested/parent.yaml",
            include_str!("assets/tpl_nested/parent.yaml"),
        ),
        Asset::new(
            "assets/tpl_nested/child/child.yaml",
            include_str!("assets/tpl_nested/child/child.yaml"),
        ),
        Asset::new(
            "assets/tpl_nested/child/example_child_lambda/handler.js",
            include_str!("assets/tpl_nested/child/example_child_lambda/handler.js"),
        ),
        Asset::new(
            "assets/tpl_nested/example_parent_lambda/handler.js",
            include_str!("assets/tpl_nested/example_parent_lambda/handler.js"),
        ),
    ]
}
